# Copyright 2023 opennaslab
# SPDX-License-Identifier: Apache-2.0

name: Build bifrost steps image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v39
  
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.ORG_DOCKERHUB_USER }}
        password: ${{ secrets.ORG_DOCKERHUB_PASSWORD }}

    - name: Build and push steps image
      run: |
        cache_file=$(mktemp)
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          step_path=$(hack/build-step.sh ${file} ${cache_file})
        done
